version: '3.8'

services:
    postgres:
        image: postgres:16-alpine
        container_name: url-shortener-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: url_shortener
            POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - url-shortener-network

volumes:
    postgres_data:
        driver: local

networks:
    url-shortener-network:
        driver: bridge
