name: Deploy to Render

on:
    push:
        branches: [main]

jobs:
    test:
        name: Build And Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Run lint
              run: npm run lint
            - name: Build project
              run: npm run build

    migrate:
        name: Database Migration
        runs-on: ubuntu-latest
        needs: test
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Generate Prisma client
              run: npx prisma generate
            - name: Run database migrations
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
              run: npx prisma migrate deploy
            - name: Check migration status
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
              run: npx prisma migrate status

    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        needs: [test, migrate]
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Trigger Render Deploy
              run: |
                  response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.RENDER_DEPLOY_HOOK }})
                  if [ $response -eq 200 ]; then
                    echo "✅ Deploy triggered successfully"
                  else
                    echo "❌ Deploy failed (HTTP $response)"
                    exit 1
                  fi
            - name: Deployment notification
              run: |
                  echo "🚀 Deployment initiated!"
                  echo "📊 Monitor progress at: https://dashboard.render.com"
